-- PK Supplier Hub — install
CREATE TABLE IF NOT EXISTS `PREFIX_pksh_source` (
  `id_source` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_shop` INT UNSIGNED NOT NULL DEFAULT 1,
  `active` TINYINT(1) NOT NULL DEFAULT 0,
  `name` VARCHAR(128) NOT NULL,
  `url` TEXT NULL,
  `file_type` ENUM('csv','xml','json') NOT NULL DEFAULT 'csv',
  `auth_type` ENUM('none','basic','bearer','header','query') NOT NULL DEFAULT 'none',
  `auth_login` VARCHAR(128) NULL,
  `auth_password` VARCHAR(255) NULL,
  `auth_token` VARCHAR(512) NULL,
  `headers` TEXT NULL,
  `query_params` TEXT NULL,
  `delimiter` VARCHAR(2) NULL DEFAULT ';',
  `enclosure` VARCHAR(2) NULL DEFAULT '\"',
  `items_path` VARCHAR(255) NULL,
  `item_xpath` VARCHAR(255) NULL,
  `map_col_key` VARCHAR(64) NOT NULL,
  `map_col_price` VARCHAR(64) NOT NULL,
  `map_col_qty` VARCHAR(64) NOT NULL,
  `map_col_variant` VARCHAR(64) NULL,
  `key_type` ENUM('ean','reference','supplier_reference') NOT NULL DEFAULT 'ean',
  `price_currency` ENUM('PLN','EUR') NOT NULL DEFAULT 'PLN',
  `rate_mode` ENUM('ecb','fixed') NOT NULL DEFAULT 'ecb',
  `fixed_rate` DECIMAL(10,6) NULL,
  `margin_mode` ENUM('fixed','tiered') NOT NULL DEFAULT 'fixed',
  `margin_fixed_pct` DECIMAL(6,3) NOT NULL DEFAULT 0.000,
  `margin_tiers` MEDIUMTEXT NULL,
  `ending_mode` ENUM('none','fixed99','custom') NOT NULL DEFAULT 'none',
  `ending_value` VARCHAR(8) NULL,
  `min_margin_pct` DECIMAL(6,3) NOT NULL DEFAULT 0.000,
  `max_delta_pct` DECIMAL(6,3) NOT NULL DEFAULT 50.000,
  `zero_qty_policy` ENUM('disable','backorder','none') NOT NULL DEFAULT 'disable',
  `stock_buffer` INT NOT NULL DEFAULT 0,
  `price_update_mode` ENUM('impact','specific_price') NOT NULL DEFAULT 'impact',
  `tax_rule_group_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `last_run_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_source`),
  KEY `idx_shop_active` (`id_shop`,`active`),
  KEY `idx_key_type` (`key_type`),
  KEY `idx_price_mode` (`price_update_mode`)
) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PREFIX_pksh_run` (
  `id_run` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_shop` INT UNSIGNED NOT NULL,
  `id_source` INT UNSIGNED NOT NULL,
  `started_at` DATETIME NOT NULL,
  `finished_at` DATETIME NULL,
  `status` ENUM('running','ok','error','aborted') NOT NULL DEFAULT 'running',
  `total` INT NOT NULL DEFAULT 0,
  `updated` INT NOT NULL DEFAULT 0,
  `skipped` INT NOT NULL DEFAULT 0,
  `errors` INT NOT NULL DEFAULT 0,
  `dry_run` TINYINT(1) NOT NULL DEFAULT 1,
  `locked` TINYINT(1) NOT NULL DEFAULT 0,
  `checksum` VARCHAR(64) NULL,
  `message` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_run`),
  KEY `idx_source_time` (`id_source`,`started_at`),
  KEY `idx_status` (`status`)
) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PREFIX_pksh_log` (
  `id_log` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_run` INT UNSIGNED NOT NULL,
  `id_product` INT UNSIGNED NULL,
  `id_product_attribute` INT UNSIGNED NULL,
  `key_value` VARCHAR(64) NULL,
  `action` ENUM('price','stock','skip','error','nochange','disable','enable','rollback') NOT NULL,
  `old_price` DECIMAL(20,6) NULL,
  `new_price` DECIMAL(20,6) NULL,
  `old_qty` INT NULL,
  `new_qty` INT NULL,
  `reason` VARCHAR(255) NULL,
  `details` MEDIUMTEXT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_log`),
  KEY `idx_run` (`id_run`),
  KEY `idx_product` (`id_product`),
  KEY `idx_action` (`action`)
) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PREFIX_pksh_snapshot` (
  `id_snapshot` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_run` INT UNSIGNED NOT NULL,
  `id_product` INT UNSIGNED NOT NULL,
  `id_product_attribute` INT UNSIGNED NULL,
  `price` DECIMAL(20,6) NULL,
  `quantity` INT NULL,
  `active` TINYINT(1) NULL,
  `extra` MEDIUMTEXT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_snapshot`),
  KEY `idx_run_product` (`id_run`,`id_product`)
) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8mb4;
